import { Model, DataTypes } from 'sequelize';
import { sequelize } from '../config/db.js';

const Configuration = sequelize.define( "Configuration",
    {
        tds: DataTypes.STRING(255),
        serviceCharge: DataTypes.STRING(255),
        pairPrice: DataTypes.STRING(255),
        pairCeiling: DataTypes.STRING(255),
        pairCeilingType: DataTypes.STRING(255),
        productPointValue: DataTypes.STRING(255),
        pairValue: DataTypes.STRING(255),
        startDate: DataTypes.STRING(255),
        endDate: DataTypes.STRING(255),
        smsStatus: DataTypes.STRING(255),
        regAmount: DataTypes.STRING(255),
        referralAmount: DataTypes.STRING(255),
        maxPinCount: DataTypes.STRING(255),
        pairCommissionType: DataTypes.STRING(255),
        depthCeiling: DataTypes.STRING(255),
        widthCeiling: DataTypes.STRING(255),
        levelCommissionType: DataTypes.STRING(255),
        transFee: DataTypes.STRING(255),
        overrideCommission: DataTypes.STRING(255),
        profileUpdationHistory: DataTypes.STRING(255),
        xupLevel: DataTypes.STRING(255),
        uploadConfig: DataTypes.STRING(255),
        pairCeilingMonthly: DataTypes.STRING(255),
        poolBonusPercent: DataTypes.STRING(255),
        sponsorCommissionType: DataTypes.STRING(255),
        purchaseIncomePerc: DataTypes.STRING(255),
        commissionCriteria: DataTypes.STRING(255),
        referralCommissionType: DataTypes.STRING(255),
        commissionUptoLevel: DataTypes.STRING(255),
        roiPeriod: DataTypes.STRING(255),
        roiDaysSkip: DataTypes.STRING(255),
        roiCriteria: DataTypes.STRING(255),
        skipBlockedUsersCommission: DataTypes.STRING(255),
        poolBonusPeriod: DataTypes.STRING(255),
        poolBonusCriteria: DataTypes.STRING(255),
        poolDistributionCriteria: DataTypes.STRING(255),
        matchingCriteria: DataTypes.STRING(255),
        matchingUptoLevel: DataTypes.STRING(255),
        salesCriteria: DataTypes.STRING(255),
        salesType: DataTypes.STRING(255),
        salesLevel: DataTypes.STRING(255),
        apiKey: DataTypes.TEXT,
        treeIconBased: DataTypes.STRING(255),
        activeTreeIcon: DataTypes.STRING(255),
        inactiveTreeIcon: DataTypes.STRING(255),
        defaultPackageTreeIcon: DataTypes.STRING(255),
        defaultRankTreeIcon: DataTypes.STRING(255),
        treeDepth: DataTypes.INTEGER(),
        treeWidth: DataTypes.INTEGER(),
        // replicaHashKey: DataTypes.TEXT,
    }, { sequelize }
);

export default Configuration;

