<?php

namespace Database\Seeders;

use App\Models\CurrencyDetail;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencyDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currency_details')->delete();
        $data = [
            [
                'title' => 'United Arab Emirates Dirham',
                'code' => 'AED',
                'value' => '3.6731515325845',
                'symbol_left' => 'د.إ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Afghan Afghani',
                'code' => 'AFN',
                'value' => '75.618523611413',
                'symbol_left' => '؋',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Albanian Lek',
                'code' => 'ALL',
                'value' => '108.64982951795',
                'symbol_left' => 'Lek',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Armenian Dram',
                'code' => 'AMD',
                'value' => '485.39901481721',
                'symbol_left' => 'դր.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Netherlands Antillean Guilder',
                'code' => 'ANG',
                'value' => '1.7718504668963',
                'symbol_left' => 'ƒ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Angolan Kwanza',
                'code' => 'AOA',
                'value' => '310.28312122466',
                'symbol_left' => 'Kz',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Argentine Peso',
                'code' => 'ARS',
                'value' => '37.475515129405',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Australian Dollar',
                'code' => 'AUD',
                'value' => '1.3946501610108',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Aruban Florin',
                'code' => 'AWG',
                'value' => '1.8015006629858',
                'symbol_left' => 'ƒ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Azerbaijani Manat',
                'code' => 'AZN',
                'value' => '1.7050406210317',
                'symbol_left' => 'man',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [

                'title' => 'Bosnia-Herzegovina Convertible Mark',
                'code' => 'BAM',
                'value' => '1.7158974511881',
                'symbol_left' => 'KM',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [

                'title' => 'Barbadian Dollar',
                'code' => 'BBD',
                'value' => '1.9981004932053',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'value' => '83.925014206838',
                'symbol_left' => '৳',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bulgarian Lev',
                'code' => 'BGN',
                'value' => '1.7153511018192',
                'symbol_left' => 'лв',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahraini Dinar',
                'code' => 'BHD',
                'value' => '0.37701965103798',
                'symbol_left' => '.د.ب ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Burundian Franc',
                'code' => 'BIF',
                'value' => '1790.950569852',
                'symbol_left' => 'FBu',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Bermudan Dollar',
                'code' => 'BMD',
                'value' => 1,
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Brunei Dollar',
                'code' => 'BND',
                'value' => '1.5759258999418',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Bolivian Boliviano',
                'code' => 'BOB',
                'value' => '6.9149527841894',
                'symbol_left' => '$b',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Brazilian Real',
                'code' => 'BRL',
                'value' => '3.7356028610115',
                'symbol_left' => 'R$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Bahamian Dollar',
                'code' => 'BSD',
                'value' => '1.0000499870209',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Bitcoin',
                'code' => 'BTC',
                'value' => '0.00027712102822425',
                'symbol_left' => '฿',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Bhutanese Ngultrum',
                'code' => 'BTN',
                'value' => '71.036887790539',
                'symbol_left' => 'Nu.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Botswanan Pula',
                'code' => 'BWP',
                'value' => '10.486050113304',
                'symbol_left' => 'P',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'New Belarusian Ruble',
                'code' => 'BYN',
                'value' => '2.1532049573093',
                'symbol_left' => 'Br',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Belarusian Ruble',
                'code' => 'BYR',
                'value' => '19600.006239608',
                'symbol_left' => 'Br',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Belize Dollar',
                'code' => 'BZD',
                'value' => '2.0064509565937',
                'symbol_left' => 'BZ$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Canadian Dollar',
                'code' => 'CAD',
                'value' => '1.3278508387296',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Congolese Franc',
                'code' => 'CDF',
                'value' => '1630.0003665715',
                'symbol_left' => 'FC',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Swiss Franc',
                'code' => 'CHF',
                'value' => '0.9921950090152',
                'symbol_left' => 'CHF',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Chilean Unit of Account (UF)',
                'code' => 'CLF',
                'value' => '0.025047882304244',
                'symbol_left' => 'CLF',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Chilean Peso',
                'code' => 'CLP',
                'value' => '668.90274104268',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Chinese Yuan',
                'code' => 'CNY',
                'value' => '6.7705025712622',
                'symbol_left' => '¥',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Colombian Peso',
                'code' => 'COP',
                'value' => '3117.6009921985',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Costa Rican Colón',
                'code' => 'CRC',
                'value' => '600.70516427314',
                'symbol_left' => '₡',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cuban Convertible Peso',
                'code' => 'CUC',
                'value' => 1,
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Cuban Peso',
                'code' => 'CUP',
                'value' => '26.500008769653',
                'symbol_left' => '₱',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Cape Verdean Escudo',
                'code' => 'CVE',
                'value' => '96.840529125771',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Czech Republic Koruna',
                'code' => 'CZK',
                'value' => '22.403995979991',
                'symbol_left' => 'Kč',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Djiboutian Franc',
                'code' => 'DJF',
                'value' => '177.72013319349',
                'symbol_left' => 'Fdj',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Danish Krone',
                'code' => 'DKK',
                'value' => '6.5464624974568',
                'symbol_left' => 'kr.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Dominican Peso',
                'code' => 'DOP',
                'value' => '50.485040726268',
                'symbol_left' => 'RD$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Algerian Dinar',
                'code' => 'DZD',
                'value' => '118.39041266478',
                'symbol_left' => 'دج',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Egyptian Pound',
                'code' => 'EGP',
                'value' => '17.919302531974',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Eritrean Nakfa',
                'code' => 'ERN',
                'value' => '15.000420943334',
                'symbol_left' => 'ናቕፋ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Ethiopian Birr',
                'code' => 'ETB',
                'value' => '28.211506486035',
                'symbol_left' => 'ብር',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Euro',
                'code' => 'EUR',
                'value' => '0.87696527919067',
                'symbol_left' => '€',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Fijian Dollar',
                'code' => 'FJD',
                'value' => '2.1164986985835',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Falkland Islands Pound',
                'code' => 'FKP',
                'value' => '0.77999045861776',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'British Pound Sterling',
                'code' => 'GBP',
                'value' => '0.77530483313105',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Georgian Lari',
                'code' => 'GEL',
                'value' => '2.6649510302588',
                'symbol_left' => 'ლ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Guernsey Pound',
                'code' => 'GGP',
                'value' => '0.7755766923676',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Ghanaian Cedi',
                'code' => 'GHS',
                'value' => '4.8987973298161',
                'symbol_left' => '₵',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Gibraltar Pound',
                'code' => 'GIP',
                'value' => '0.77999484344416',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Gambian Dalasi',
                'code' => 'GMD',
                'value' => '49.555004139276',
                'symbol_left' => 'D',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Guinean Franc',
                'code' => 'GNF',
                'value' => '9106.5528169879',
                'symbol_left' => 'FG',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Guatemalan Quetzal',
                'code' => 'GTQ',
                'value' => '7.7189527982208',
                'symbol_left' => 'Q',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Guyanaese Dollar',
                'code' => 'GYD',
                'value' => '208.52510663898',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'value' => '7.8440518952974',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Honduran Lempira',
                'code' => 'HNL',
                'value' => '24.351028154093',
                'symbol_left' => 'L',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Croatian Kuna',
                'code' => 'HRK',
                'value' => '6.5133053172159',
                'symbol_left' => 'kn',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Haitian Gourde',
                'code' => 'HTG',
                'value' => '78.246523709633',
                'symbol_left' => 'G',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Hungarian Forint',
                'code' => 'HUF',
                'value' => '281.36512010916',
                'symbol_left' => 'Ft',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'value' => '14190.004517248',
                'symbol_left' => 'Rp',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Israeli New Sheqel',
                'code' => 'ILS',
                'value' => '3.6877416039344',
                'symbol_left' => '₪',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Manx pound',
                'code' => 'IMP',
                'value' => '0.7755766923676',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Indian Rupee',
                'code' => 'INR',
                'value' => '71.038523330784',
                'symbol_left' => '₹',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Iraqi Dinar',
                'code' => 'IQD',
                'value' => '1191.1503793752',
                'symbol_left' => 'ع.د',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Iranian Rial',
                'code' => 'IRR',
                'value' => '42105.013901654',
                'symbol_left' => '﷼',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Icelandic Króna',
                'code' => 'ISK',
                'value' => '120.68999978953',
                'symbol_left' => 'kr',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Jersey Pound',
                'code' => 'JEP',
                'value' => '0.7755766923676',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Jamaican Dollar',
                'code' => 'JMD',
                'value' => '129.91979714039',
                'symbol_left' => 'J$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Jordanian Dinar',
                'code' => 'JOD',
                'value' => '0.70959820958769',
                'symbol_left' => 'د.ا',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Japanese Yen',
                'code' => 'JPY',
                'value' => '108.83504721581',
                'symbol_left' => '¥',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [

                'title' => 'Kenyan Shilling',
                'code' => 'KES',
                'value' => '101.6697717084',
                'symbol_left' => 'KSh,',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kyrgystani Som',
                'code' => 'KGS',
                'value' => '69.849318948764',
                'symbol_left' => 'лв',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Cambodian Riel',
                'code' => 'KHR',
                'value' => '4014.5511069056',
                'symbol_left' => '៛',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Comorian Franc',
                'code' => 'KMF',
                'value' => '431.62511049763',
                'symbol_left' => 'CF',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'North Korean Won',
                'code' => 'KPW',
                'value' => '900.06504012993',
                'symbol_left' => '₩',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'South Korean Won',
                'code' => 'KRW',
                'value' => '1123.8203904951',
                'symbol_left' => '₩',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'value' => '0.30315023467591',
                'symbol_left' => 'د.ك ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Cayman Islands Dollar',
                'code' => 'KYD',
                'value' => '0.83197520643763',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Kazakhstani Tenge',
                'code' => 'KZT',
                'value' => '378.00976150052',
                'symbol_left' => 'лв',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Laotian Kip',
                'code' => 'LAK',
                'value' => '8546.0530353522',
                'symbol_left' => '₭',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Lebanese Pound',
                'code' => 'LBP',
                'value' => '1507.5503790244',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'value' => '181.60614700043',
                'symbol_left' => '₨',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Liberian Dollar',
                'code' => 'LRD',
                'value' => '159.51290629801',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Lesotho Loti',
                'code' => 'LSL',
                'value' => '13.699204417099',
                'symbol_left' => 'L ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Lithuanian Litas',
                'code' => 'LTL',
                'value' => '2.9527412180697',
                'symbol_left' => 'Lt ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Latvian Lats',
                'code' => 'LVL',
                'value' => '0.60489030918288',
                'symbol_left' => 'Ls',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Libyan Dinar',
                'code' => 'LYD',
                'value' => '1.3804003521893',
                'symbol_left' => 'ل.د',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Moroccan Dirham',
                'code' => 'MAD',
                'value' => '9.5428029213467',
                'symbol_left' => 'DH',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Moldovan Leu',
                'code' => 'MDL',
                'value' => '17.154501111992',
                'symbol_left' => 'L',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Malagasy Ariary',
                'code' => 'MGA',
                'value' => '3653.5508271537',
                'symbol_left' => 'Ar',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Macedonian Denar',
                'code' => 'MKD',
                'value' => '53.93977090159',
                'symbol_left' => 'ден',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Myanma Kyat',
                'code' => 'MMK',
                'value' => '1523.2971018051',
                'symbol_left' => 'K',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Mongolian Tugrik',
                'code' => 'MNT',
                'value' => '2659.7811498067',
                'symbol_left' => '₮',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Macanese Pataca',
                'code' => 'MOP',
                'value' => '8.0654523036124',
                'symbol_left' => 'P',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Mauritanian Ouguiya',
                'code' => 'MRO',
                'value' => '357.00020608684',
                'symbol_left' => 'UM',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Mauritian Rupee',
                'code' => 'MUR',
                'value' => '34.352513733276',
                'symbol_left' => '₨',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Maldivian Rufiyaa',
                'code' => 'MVR',
                'value' => '15.525001403144',
                'symbol_left' => 'Rf',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Malawian Kwacha',
                'code' => 'MWK',
                'value' => '728.5498256593',
                'symbol_left' => 'MK',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Mexican Peso',
                'code' => 'MXN',
                'value' => '18.9324964746',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'value' => '4.1132512961547',
                'symbol_left' => 'RM',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Mozambican Metical',
                'code' => 'MZN',
                'value' => '61.735036341441',
                'symbol_left' => 'MT',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Namibian Dollar',
                'code' => 'NAD',
                'value' => '13.880084644689',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Nigerian Naira',
                'code' => 'NGN',
                'value' => '362.37025386391',
                'symbol_left' => '₦',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Nicaraguan Córdoba',
                'code' => 'NIO',
                'value' => '32.438508071588',
                'symbol_left' => 'C$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Norwegian Krone',
                'code' => 'NOK',
                'value' => '8.557133410974',
                'symbol_left' => 'kr',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Nepalese Rupee',
                'code' => 'NPR',
                'value' => '113.78989490448',
                'symbol_left' => '₨',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'New Zealand Dollar',
                'code' => 'NZD',
                'value' => '1.4833104737717',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Omani Rial',
                'code' => 'OMR',
                'value' => '0.38500529687029',
                'symbol_left' => '﷼',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Panamanian Balboa',
                'code' => 'PAB',
                'value' => '0.99995001297909',
                'symbol_left' => 'B/.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Peruvian Nuevo Sol',
                'code' => 'PEN',
                'value' => '3.3302510926987',
                'symbol_left' => 'S/.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Papua New Guinean Kina',
                'code' => 'PGK',
                'value' => '3.2521503188646',
                'symbol_left' => 'K',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Philippine Peso',
                'code' => 'PHP',
                'value' => '52.412029858914',
                'symbol_left' => '₱',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Pakistani Rupee',
                'code' => 'PKR',
                'value' => '139.88013112385',
                'symbol_left' => '₨',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Polish Zloty',
                'code' => 'PLN',
                'value' => '3.7578418235265',
                'symbol_left' => 'zł',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Paraguayan Guarani',
                'code' => 'PYG',
                'value' => '6033.3521103292',
                'symbol_left' => 'Gs',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Qatari Rial',
                'code' => 'QAR',
                'value' => '3.6410212786855',
                'symbol_left' => '﷼',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Romanian Leu',
                'code' => 'RON',
                'value' => '4.1124032707297',
                'symbol_left' => 'lei',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Serbian Dinar',
                'code' => 'RSD',
                'value' => '103.79040354434',
                'symbol_left' => 'Дин.',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Russian Ruble',
                'code' => 'RUB',
                'value' => '66.485999249318',
                'symbol_left' => '₽',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Rwandan Franc',
                'code' => 'RWF',
                'value' => '893.21028399644',
                'symbol_left' => 'FRw',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Saudi Riyal',
                'code' => 'SAR',
                'value' => '3.7510514813697',
                'symbol_left' => '﷼',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Solomon Islands Dollar',
                'code' => 'SBD',
                'value' => '8.1036529111739',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Seychellois Rupee',
                'code' => 'SCR',
                'value' => '13.646038397048',
                'symbol_left' => '₨',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Sudanese Pound',
                'code' => 'SDG',
                'value' => '47.535519724703',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Swedish Krona',
                'code' => 'SEK',
                'value' => '9.0169131523745',
                'symbol_left' => 'kr',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Singapore Dollar',
                'code' => 'SGD',
                'value' => '1.356021594393',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Saint Helena Pound',
                'code' => 'SHP',
                'value' => '1.3208973810309',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Sierra Leonean Leone',
                'code' => 'SLL',
                'value' => '8600.0030886717',
                'symbol_left' => 'Le',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Somali Shilling',
                'code' => 'SOS',
                'value' => '585.00051039379',
                'symbol_left' => 'S',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Surinamese Dollar',
                'code' => 'SRD',
                'value' => '7.4580258108421',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'São Tomé and Príncipe Dobra',
                'code' => 'STD',
                'value' => '21050.60631187',
                'symbol_left' => ' Db',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Salvadoran Colón',
                'code' => 'SVC',
                'value' => '8.7356528480324',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Syrian Pound',
                'code' => 'SYP',
                'value' => '514.99971674021',
                'symbol_left' => '£',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Swazi Lilangeni',
                'code' => 'SZL',
                'value' => '13.705501027803',
                'symbol_left' => 'E ',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Thai Baht',
                'code' => 'THB',
                'value' => '31.734980215663',
                'symbol_left' => '฿',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Tajikistani Somoni',
                'code' => 'TJS',
                'value' => '9.4138022057431',
                'symbol_left' => 'ЅM',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Turkmenistani Manat',
                'code' => 'TMT',
                'value' => '3.5000008769653',
                'symbol_left' => 'm',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Tunisian Dinar',
                'code' => 'TND',
                'value' => '2.9613951114447',
                'symbol_left' => 'د.ت',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Tongan Paʻanga',
                'code' => 'TOP',
                'value' => '2.3376991588149',
                'symbol_left' => 'T$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Turkish Lira',
                'code' => 'TRY',
                'value' => '5.3624918442229',
                'symbol_left' => '₺',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Trinidad and Tobago Dollar',
                'code' => 'TTD',
                'value' => '6.7928520314024',
                'symbol_left' => 'TT$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'New Taiwan Dollar',
                'code' => 'TWD',
                'value' => '30.85103429285',
                'symbol_left' => 'NT$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'value' => '2305.0839878418',
                'symbol_left' => 'TSh',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'value' => '28.030093063555',
                'symbol_left' => '₴',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Ugandan Shilling',
                'code' => 'UGX',
                'value' => '3693.6001608354',
                'symbol_left' => 'USh',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'United States Dollar',
                'code' => 'USD',
                'value' => 1,
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 1,
                'default' => 1,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Uruguayan Peso',
                'code' => 'UYU',
                'value' => '32.740223591068',
                'symbol_left' => '$U',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Uzbekistan Som',
                'code' => 'UZS',
                'value' => '8332.0528354041',
                'symbol_left' => 'лв',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Venezuelan Bolívar Fuerte',
                'code' => 'VEF',
                'value' => '9.9875006138757',
                'symbol_left' => 'Bs',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Vietnamese Dong',
                'code' => 'VND',
                'value' => '23195.507384925',
                'symbol_left' => '₫',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Vanuatu Vatu',
                'code' => 'VUV',
                'value' => '113.67784943559',
                'symbol_left' => 'VT',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Samoan Tala',
                'code' => 'WST',
                'value' => '2.601853378421',
                'symbol_left' => 'WS$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'value' => '575.49020342087',
                'symbol_left' => 'FCFA',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Silver (troy ounce)',
                'code' => 'XAG',
                'value' => '0.064143871415843',
                'symbol_left' => 'XAG',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Gold (troy ounce)',
                'code' => 'XAU',
                'value' => '0.00077260641096698',
                'symbol_left' => 'XAU',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'value' => '2.7025509166041',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Special Drawing Rights',
                'code' => 'XDR',
                'value' => '0.71761016437837',
                'symbol_left' => 'XDR',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'value' => '575.48997891775',
                'symbol_left' => 'CFA',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'CFP Franc',
                'code' => 'XPF',
                'value' => '104.63005044304',
                'symbol_left' => '₣',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Yemeni Rial',
                'code' => 'YER',
                'value' => '250.34977146285',
                'symbol_left' => '﷼',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'South African Rand',
                'code' => 'ZAR',
                'value' => '13.716154402015',
                'symbol_left' => 'R',
                'symbol_right' => '',
                'status' => 1,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'title' => 'Zambian Kwacha (pre-2013)',
                'code' => 'ZMK',
                'value' => '9001.2050081733',
                'symbol_left' => 'ZK',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [

                'title' => 'Zambian Kwacha',
                'code' => 'ZMW',
                'value' => '11.902989223851',
                'symbol_left' => 'ZK',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Zimbabwean Dollar',
                'code' => 'ZWL',
                'value' => '322.35511393533',
                'symbol_left' => '$',
                'symbol_right' => '',
                'status' => 0,
                'default' => 0,
                'delete_status' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),

            ],
        ];
        CurrencyDetail::insert($data);
    }
}
