<?php

namespace Database\Seeders;

use App\Models\Menu;
use App\Models\ModuleStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settingsMenu = [
            [
                'title' => 'Binary Configurations',
                'slug' => Str::slug('Binary Configurations'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'side_menu' => 0,
                'route_name' => 'binaryConfig',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Replica Management',
                'slug' => Str::slug('Replica Management'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 0,
                'side_menu' => 0,
                'route_name' => 'replica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ROI',
                'slug' => Str::slug('ROI'),
                'parent_id' => null,
                'order' => 12,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'side_menu' => 0,

                'route_name' => 'roicommission',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Matching Bonus',
                'slug' => Str::slug('Matching Bonus'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'side_menu' => 0,

                'route_name' => 'matching_bonus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pool Bonus',
                'slug' => Str::slug('Pool Bonus'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'side_menu' => 0,

                'route_name' => 'poolbonus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fast Start Bonus',
                'slug' => Str::slug('Fast Start Bonus'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'side_menu' => 0,

                'is_child' => 0,
                'settings_menu' => 1,
                'route_name' => 'faststartbonus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Performance Bonus',
                'slug' => Str::slug('Performance Bonus'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'side_menu' => 0,

                'has_children' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'route_name' => 'performance_bonus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rank',
                'slug' => Str::slug('Rank'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'side_menu' => 0,

                'settings_menu' => 1,
                'route_name' => 'rank',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Plan Settings',
                'slug' => Str::slug('Plan Settings'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'side_menu' => 0,

                'is_child' => 0,
                'settings_menu' => 1,
                'route_name' => 'settings.plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Commission History',
                'slug' => Str::slug('Commission History'),
                'parent_id' => null,
                'order' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'side_menu' => 0,
                'is_child' => 0,
                'settings_menu' => 1,
                'route_name' => 'manage.commission',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        $parentMenus = [
            [
                'title' => 'Dashboard',
                'slug' => 'dashboard',
                'parent_id' => null,
                'order' => 1,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-home-circle',
                'user_icon' => 'dashboard_ico.svg',
                'route_name' => 'dashboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'HYIP/ROI Cron',
                'slug' => 'hyiproi-cron',
                'parent_id' => null,
                'order' => 4,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-brightness',
                'user_icon' => null,

                'route_name' => 'hyip-roi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Profile Management',
                'slug' => 'profile-management',
                'parent_id' => null,
                'order' => 12,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-user',
                'user_icon' => null,

                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Settings',
                'slug' => 'settings',
                'parent_id' => null,
                'order' => 18,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-cog',
                'route_name' => 'javascript: void(0);',
                'user_icon' => null,

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Networks',
                'slug' => 'networks',
                'parent_id' => null,
                'order' => 2,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'user_icon' => 'network_ico.svg',
                'admin_icon' => 'bx bx-git-repo-forked',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business',
                'slug' => 'business',
                'parent_id' => null,
                'order' => 8,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-briefcase',
                'user_icon' => null,

                'route_name' => 'reports.business',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reports',
                'slug' => 'reports',
                'parent_id' => null,
                'order' => 15,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-bar-chart',
                'user_icon' => null,

                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tools',
                'slug' => 'tools',
                'parent_id' => null,
                'order' => 17,
                'react' => 1,
                'react_only' => 0,
                'admin_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'user_icon' => 'tool.svg',
                'admin_icon' => 'bx bx-wrench',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'E Wallet',
                'slug' => 'e-wallet',
                'parent_id' => null,
                'order' => 9,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'wallet_ico.svg',
                'admin_icon' => 'bx bx-wallet',
                'route_name' => 'ewallet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Payout',
                'slug' => 'payout',
                'parent_id' => null,
                'order' => 10,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'payout_ico.svg',
                'admin_icon' => 'bx bx-money',
                'route_name' => 'reports.payout',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Package',
                'slug' => 'package',
                'parent_id' => null,
                'order' => 13,
                'react' => 0,

                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-cart',
                'user_icon' => null,

                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mail Box',
                'slug' => 'mail-box',
                'parent_id' => null,
                'admin_only' => 0,
                'order' => 19,
                'react' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'mail.svg',
                'admin_icon' => 'bx bx-envelope',
                'route_name' => 'mailBox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'E-pin',
                'slug' => 'e-pin',
                'parent_id' => null,
                'order' => 11,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'e-pin.svg',
                'admin_icon' => 'bx bx-bookmark-plus',
                'route_name' => 'epin.index',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Shopping Cart',
                'slug' => 'shopping-cart',
                'parent_id' => null,
                'order' => 14,
                'react' => 1,

                'is_heading' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'has_children' => 1,
                'is_child' => 0,
                'user_icon' => 'ShoppingBasketOutlinedIcon',
                'admin_icon' => 'bx bx-shopping-bag',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Privileged User',
                'slug' => 'privileged-user',
                'parent_id' => null,
                'order' => 16,
                'react' => 0,

                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'fas fa-user-circle',
                'user_icon' => null,

                'route_name' => 'privileged-user.index',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Support Center',
                'slug' => 'support-center',
                'parent_id' => null,
                'order' => 20,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'customer-support.svg',
                'admin_icon' => 'bx bx-support',
                'route_name' => 'support.index',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CRM',
                'slug' => 'crm',
                'parent_id' => null,
                'order' => 21,
                'react' => 1,
                'is_heading' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'has_children' => 1,
                'is_child' => 0,
                'user_icon' => 'crm.svg',
                'admin_icon' => 'bx bx-group',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Donation',
                'slug' => 'donation',
                'parent_id' => null,
                'order' => 5,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-gift',
                'user_icon' => 'VolunteerActivismOutlinedIcon',

                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Register',
                'slug' => 'register',
                'parent_id' => null,
                'order' => 3,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 1,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'user_ico.svg',
                'admin_icon' => 'bx bx-gift',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Shopping',
                'slug' => 'shopping',
                'parent_id' => null,
                'order' => 14,
                'react' => 1,
                'admin_only' => 0,
                'react_only' => 1,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'user_icon' => 'shopping-cart-white.svg',
                'admin_icon' => 'bx bx-gift',
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parties',
                'slug' => 'parties',
                'parent_id' => null,
                'order' => 5,
                'react' => 1,
                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-gift',
                'user_icon' => 'LiquorOutlinedIcon',

                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Auto Responder',
                'slug' => 'auto-responder',
                'parent_id' => null,
                'order' => 22,
                'react' => 0,
                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-envelope',
                'user_icon' => 'DraftsOutlinedIcon',
                'route_name' => 'responder.index',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Approval',
                'slug' => 'allapproval',
                'parent_id' => null,
                'order' => 4,
                'react' => 0,
                'admin_only' => 1,
                'react_only' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-user-check',
                'user_icon' => 'DraftsOutlinedIcon',
                'route_name' => 'responder.index',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        $moduleStatus = ModuleStatus::first();

        if ($moduleStatus->ecom_status) {
            $registerMenu = [
                'title' => 'Register',
                'slug' => 'register',
                'parent_id' => null,
                'admin_only' => 1,
                'react_only' => 0,
                'order' => 3,
                'react' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-user-plus',
                'user_icon' => ' StorefrontOutlinedIcon ',
                'route_name' => 'store.register',
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $storeMenu = [
                'title' => 'Store',
                'slug' => 'store',
                'parent_id' => null,
                'admin_only' => 0,
                'react_only' => 0,
                'order' => 3,
                'react' => 1,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'bx bx-store',
                'user_icon' => 'StorefrontOutlinedIcon',
                'route_name' => 'store.index',
                'created_at' => now(),
                'updated_at' => now(),
            ];
            array_push($parentMenus, $storeMenu);

            $storeAdmin = [
                'title' => 'Store Administration',
                'slug' => 'store-administration',
                'parent_id' => null,
                'admin_only' => 1,
                'react_only' => 0,
                'order' => 6,
                'react' => 0,
                'is_heading' => 1,
                'has_children' => 0,
                'is_child' => 0,
                'admin_icon' => 'mdi mdi-cart-arrow-right',
                'user_icon' => null,
                'route_name' => 'ecom.store.admin',
                'created_at' => now(),
                'updated_at' => now(),
            ];
            array_push($parentMenus, $storeAdmin);

            $orderHistory = [
                'title' => 'Order Details',
                'slug' => 'order-details',
                'parent_id' => null,
                'admin_only' => 1,
                'react_only' => 0,
                'order' => 7,
                'react' => 1,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-cart',
                'user_icon' => "ShoppingBasketOutlinedIcon",
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ];

            array_push($parentMenus, $orderHistory);
        } else {
            $registerMenu = [
                'title' => 'Sign Up',
                'slug' => 'sign-up',
                'parent_id' => null,
                'admin_only' => 1,
                'react_only' => 0,
                'order' => 3,
                'react' => 0,
                'is_heading' => 1,
                'has_children' => 1,
                'is_child' => 0,
                'admin_icon' => 'bx bx-user-plus',
                'user_icon' => null,
                'route_name' => 'javascript: void(0);',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }
        array_push($parentMenus, $registerMenu);

        DB::table('menus')->delete();

        Menu::insert($settingsMenu);
        Menu::insert($parentMenus);

        $menus = Menu::where('is_heading', 1)->get();
        $subMenus = [];
        foreach ($menus as $key => $menu) {
            if ($menu->slug == 'networks') {
                $subMenus[] = [
                    'title' => 'Tree View',
                    'slug' => Str::slug('Tree View'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'network.treeview',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Genealogy Tree',
                    'slug' => Str::slug('Genealogy Tree'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'network.genealogy',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Sponsor Tree',
                    'slug' => Str::slug('Sponsor Tree'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'network.sponsorTree',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Downline Members',
                    'slug' => Str::slug('Downline Members'),
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'network.downlineMembers',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Referral Members',
                    'slug' => Str::slug('Referral Members'),
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'network.referralMembers',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                if ($moduleStatus->mlm_plan == 'Stair_Step') {
                    $subMenus[] = [
                        'title' => 'Step View',
                        'slug' => Str::slug('Step View'),
                        'parent_id' => $menu->id,
                        'child_order' => 2,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 0,
                        'react_only' => 0,
                        'route_name' => 'network.step.view',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
                if ($moduleStatus->mlm_plan == 'Monoline') {
                    $subMenus[] = [
                        'title' => 'Re-entry Table',
                        'slug' => Str::slug('Re-entry Table'),
                        'parent_id' => $menu->id,
                        'child_order' => 2,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 0,
                        'react_only' => 0,
                        'route_name' => 'network.reentry.table',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
            } elseif ($menu->slug == 'sign-up') {
                if (!$moduleStatus->ecom_status) {
                    $subMenus[] = [
                        'title' => 'Register',
                        'slug' => Str::slug('Register'),
                        'parent_id' => $menu->id,
                        'child_order' => 1,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 0,
                        'react_only' => 0,
                        'route_name' => 'register.form',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                    $subMenus[] = [
                        'title' => 'Bulk Register',
                        'slug' => Str::slug('Bulk Register'),
                        'parent_id' => $menu->id,
                        'child_order' => 3,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 0,
                        'react_only' => 0,
                        'route_name' => 'user.bulkRegister',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
            } elseif ($menu->slug == 'profile-management') {
                $subMenus[] = [
                    'title' => 'Profile View',
                    'slug' => Str::slug('Profile View'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'profile.view',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Member List',
                    'slug' => Str::slug('Member List'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'memberlist.view',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'KYC Details',
                    'slug' => Str::slug('KYC Details'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'profile.kycDetails',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'package') {
                $subMenus[] = [
                    'title' => 'Membership',
                    'slug' => 'membership',
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'package',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Repurchase/Cart',
                    'slug' => Str::slug('Repurchase/Cart'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'package.repurchase',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'shopping-cart') {
                // $subMenus[] = [
                //     'title' => 'Products',
                //     'slug' => 'products',
                //     'parent_id' => $menu->id,
                //     'child_order' => 1,
                //     'is_heading' => 0,
                //     'has_children' => 0,
                //     'is_child' => 1,
                //     'admin_only' => 0,
                //     'react_only' => 0,
                //     'route_name' => 'products.view',
                //     'created_at' => now(),
                //     'updated_at' => now(),
                // ];
                $subMenus[] = [
                    'title' => 'Approval',
                    'slug' => 'approval',
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'order.approval',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'reports') {
                $subMenus[] = [
                    'title' => 'Profile',
                    'slug' => 'profile',
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.profile',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Activate / Deactivate',
                    'slug' => Str::slug('Activate / Deactivate'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.activateDeactivate',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Package upgrade',
                    'slug' => Str::slug('Package upgrade'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.upgradePackage',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Joining',
                    'slug' => 'joining',
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'report.join',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Commission',
                    'slug' => 'commission',
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.commission',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Total Bonus',
                    'slug' => Str::slug('Total Bonus'),
                    'parent_id' => $menu->id,
                    'child_order' => 6,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.totalbonus',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Top Earners',
                    'slug' => Str::slug('Top Earners'),
                    'parent_id' => $menu->id,
                    'child_order' => 7,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.top-earners',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Rank Achievers',
                    'slug' => Str::slug('Rank Achievers'),
                    'parent_id' => $menu->id,
                    'child_order' => 8,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.rank-achievers',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Rank Performance',
                    'slug' => Str::slug('Rank Performance'),
                    'parent_id' => $menu->id,
                    'child_order' => 9,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.rank-performance',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Payout',
                    'slug' => 'payout',
                    'parent_id' => $menu->id,
                    'child_order' => 10,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.payouts',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'E-Pin Transfer',
                    'slug' => Str::slug('E-Pin Transfer'),
                    'parent_id' => $menu->id,
                    'child_order' => 11,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.epinTransfer',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];

                $subMenus[] = [
                    'title' => 'Stair Step',
                    'slug' => Str::slug('Stair Step'),
                    'parent_id' => $menu->id,
                    'child_order' => 15,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'stairstep.commission.report',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Override Commission',
                    'slug' => Str::slug('Override Commission'),
                    'parent_id' => $menu->id,
                    'child_order' => 16,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'stairstep.commission.override',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];

                $subMenus[] = [
                    'title' => 'Purchase',
                    'slug' => 'purchase',
                    'parent_id' => $menu->id,
                    'child_order' => 18,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.purchase',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];

                $subMenus[] = [
                    'title' => 'Subscription Report',
                    'slug' => Str::slug('Subscription Report'),
                    'parent_id' => $menu->id,
                    'child_order' => 20,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.subscription',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'tools') {
                $subMenus[] = [
                    'title' => 'Leads',
                    'slug' => Str::slug('Leads'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'leads',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Replica Site',
                    'slug' => Str::slug('Replica Site'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 0,
                    'admin_only' => 0,
                    'react_only' => 1,
                    'route_name' => 'javascript: void(0);',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Download Materials',
                    'slug' => Str::slug('Download Materials'),
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 0,
                    'admin_only' => 0,
                    'react_only' => 1,
                    'route_name' => 'javascript: void(0);',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Upload Material',
                    'slug' => Str::slug('Upload Material'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'material',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'News',
                    'slug' => 'news',
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'news',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Faqs',
                    'slug' => Str::slug('Faqs'),
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'faq',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Promotion tools',
                    'slug' => Str::slug('Promotion tools'),
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'promotionalTools.index',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'settings') {
                $subMenus[] = [
                    'title' => 'Activity',
                    'slug' => 'activity',
                    'parent_id' => $menu->id,
                    'child_order' => 9,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'user.activity',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Commission Settings',
                    'slug' => Str::slug('Commission Settings'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'commission',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Advanced Settings',
                    'slug' => Str::slug('Advanced Settings'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'profile',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Company Profile',
                    'slug' => Str::slug('Company Profile'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'company.profile',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Content Management',
                    'slug' => Str::slug('Content Management'),
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'welcome.letter',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Mail Content',
                    'slug' => Str::slug('Mail Content'),
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'mailcontent',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'SMS Content',
                    'slug' => Str::slug('SMS Content'),
                    'parent_id' => $menu->id,
                    'child_order' => 6,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'smscontent',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Commission History',
                    'slug' => Str::slug('Commission History'),
                    'parent_id' => $menu->id,
                    'child_order' => 7,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'manage.commission',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'crm') {
                $subMenus[] = [
                    'title' => 'Dashboard',
                    'slug' => 'dashboard',
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'crm.index',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Add Lead',
                    'slug' => Str::slug('Add Lead'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'crm.add-lead',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'View Lead',
                    'slug' => Str::slug('View Lead'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'crm.view-lead',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Graph',
                    'slug' => 'graph',
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'crm.graph',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'donation') {
                $subMenus[] = [
                    'title' => 'Recieved Donation',
                    'slug' => Str::slug('Recieved Donation'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.receivedDonation',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Given Donation',
                    'slug' => Str::slug('Given Donation'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'reports.givenDonation',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Missed Donation',
                    'slug' => Str::slug('Missed Donation'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'reports.missedDonation',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Manage User Level',
                    'slug' => Str::slug('Manage User Level'),
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'donation.manageUserLevel',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Send Donation',
                    'slug' => Str::slug('Send Donation'),
                    'parent_id' => $menu->id,
                    'child_order' => 5,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 1,
                    'route_name' => 'javascript:void;',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'parties') {
                $subMenus[] = [
                    'title' => 'Setup Party',
                    'slug' => Str::slug('Setup Party'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'party.create',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'My Party Portal',
                    'slug' => Str::slug('My Party Portal'),
                    'parent_id' => $menu->id,
                    'child_order' => 2,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 1,
                    'react_only' => 0,
                    'route_name' => 'party.partyPortal',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Host Management',
                    'slug' => Str::slug('Host Management'),
                    'parent_id' => $menu->id,
                    'child_order' => 3,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'host.management',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $subMenus[] = [
                    'title' => 'Guest Management',
                    'slug' => Str::slug('Guest Management'),
                    'parent_id' => $menu->id,
                    'child_order' => 4,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'guest.index',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            } elseif ($menu->slug == 'order-details') {
                $subMenus[] = [
                    'title' => 'Order History',
                    'slug' => Str::slug('Order History'),
                    'parent_id' => $menu->id,
                    'child_order' => 1,
                    'is_heading' => 0,
                    'has_children' => 0,
                    'is_child' => 1,
                    'admin_only' => 0,
                    'react_only' => 0,
                    'route_name' => 'ecom.order.history',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];

            }
            elseif ($menu->slug == 'allapproval') {
                if (!$moduleStatus->ecom_status) {
                    $subMenus[] = [
                        'title' => 'Registration Approval',
                        'slug' => Str::slug('Registration Approval'),
                        'parent_id' => $menu->id,
                        'child_order' => 1,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 1,
                        'react_only' => 0,
                        'route_name' => 'approval.index',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
                if(!$moduleStatus->ecom_status && $moduleStatus->package_upgrade){
                    $subMenus[] = [
                        'title' => 'Upgrade Approval',
                        'slug' => Str::slug('Upgrade Approval'),
                        'parent_id' => $menu->id,
                        'child_order' => 2,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 1,
                        'react_only' => 0,
                        'route_name' => 'package-upgrade.view',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
                if (!$moduleStatus->ecom_status && $moduleStatus->subscription_status){
                    $subMenus[] = [
                        'title' => 'Renewal Approval',
                        'slug' => Str::slug('Renewal Approval'),
                        'parent_id' => $menu->id,
                        'child_order' => 3,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 1,
                        'react_only' => 0,
                        'route_name' => 'package-renewal.view',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
                if ($moduleStatus->ecom_status) {
                    $subMenus[] = [
                        'title' => 'Order Approval',
                        'slug' => Str::slug('Order Approval'),
                        'parent_id' => $menu->id,
                        'child_order' => 2,
                        'is_heading' => 0,
                        'has_children' => 0,
                        'is_child' => 1,
                        'admin_only' => 1,
                        'react_only' => 0,
                        'route_name' => 'ecom.order.approval',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
            }

        }
        Menu::insert($subMenus);
    }
}
